'use strict';

angular
  .module('xbertsApp', [
    'ngAnimate',
    'ngCookies',
    'ngMessages',
    'ngResource',
    'ngRoute',
    'ngSanitize',
    'ngImgCrop',
    'ngFileUpload',
    'ngIdle',
    'angularMoment',
    'angular-growl',
    'ui.router',
    'infinite-scroll',
    'LocalStorageModule',
    'summernote',
    'ui.bootstrap',
    'internationalPhoneNumber',
    'duScroll',
    'dcbImgFallback',
    'configuration.properties',
    'satellizer',
    'checklist-model',
    'angularRandomString',
    '720kb.socialshare',
    'timer',
    'config',
    'mgcrea.ngStrap',
    'ngMaterial',
  ]);
